"use client";

import {useDeferredValue,useMemo,useRef,useState} from "react";
import {
  actionNeedsAmount,actions,assessPreflopAllIn,calculateHandMath,fieldLeftOptions,formatBB,handReviewSummary,positions,ranks,requiredBoardCards,streets,suits,
  tableSizes,tournamentPhases,tournamentTypes,trim,validateHandReview,
  type Card,type FieldLeft,type HandAction,type HandGameMode,type HandReviewInput,type Position,type Rank,type Street,type Suit,type TableSize,type TournamentPhase,type TournamentType,
} from "@/lib/hand-review";
import type {VisionHandDraft} from "@/lib/vision-hand-draft";
import styles from "./HandReviewWorkspace.module.css";

type PickerTarget={kind:"hero"|"board";index:number}|null;
const emptyInput:HandReviewInput={game:"CASH",tournamentTypes:[],tournamentPhase:null,fieldLeft:null,tableSize:null,bigBlind:null,ante:0,pot:null,heroPosition:null,villainPositions:[],heroStack:null,villainStacks:{},street:"PREFLOP",board:[],heroCards:[],villainActions:{},villainActionAmounts:{},heroAction:null,heroActionAmount:null,notes:""};

export default function HandReviewWorkspace(){
  const[input,setInput]=useState<HandReviewInput>(emptyInput);
  const[submitted,setSubmitted]=useState(false);
  const[picker,setPicker]=useState<PickerTarget>(null);
  const[pickRank,setPickRank]=useState<Rank|null>(null);
  const[pickSuit,setPickSuit]=useState<Suit|null>(null);
  const[visionFile,setVisionFile]=useState<File|null>(null);
  const[visionPreview,setVisionPreview]=useState("");
  const[visionDraft,setVisionDraft]=useState<VisionHandDraft|null>(null);
  const[visionBusy,setVisionBusy]=useState(false);
  const[visionError,setVisionError]=useState("");
  const[visionContext,setVisionContext]=useState("");
  const[aiAnswer,setAiAnswer]=useState("");
  const[aiBusy,setAiBusy]=useState(false);
  const[aiFallback,setAiFallback]=useState(false);
  const cameraRef=useRef<HTMLInputElement>(null);
  const galleryRef=useRef<HTMLInputElement>(null);
  const deferredInput=useDeferredValue(input);
  const math=useMemo(()=>calculateHandMath(deferredInput),[deferredInput]);
  const validation=submitted?validateHandReview(input):null;

  function changed(){setSubmitted(false)}
  function patch<K extends keyof HandReviewInput>(key:K,value:HandReviewInput[K]){setInput(prev=>({...prev,[key]:value}));changed()}
  function toggleNullable<K extends "tournamentPhase"|"fieldLeft"|"tableSize">(key:K,value:HandReviewInput[K]){setInput(prev=>({...prev,[key]:prev[key]===value?null:value}));changed()}
  function setGame(game:HandGameMode){setInput(prev=>prev.game===game?prev:{...prev,game,...(game==="CASH"?{tournamentTypes:[],tournamentPhase:null,fieldLeft:null}:{})});changed()}
  function toggleTournamentType(value:TournamentType){setInput(prev=>({...prev,tournamentTypes:prev.tournamentTypes.includes(value)?prev.tournamentTypes.filter(v=>v!==value):[...prev.tournamentTypes,value]}));changed()}
  function selectHeroPosition(position:Position){setInput(prev=>{const next=prev.heroPosition===position?null:position;return{...prev,heroPosition:next,villainPositions:next?prev.villainPositions.filter(p=>p!==next):prev.villainPositions}});changed()}
  function toggleVillain(position:Position){setInput(prev=>{if(position===prev.heroPosition)return prev;const exists=prev.villainPositions.includes(position);const villainPositions=exists?prev.villainPositions.filter(p=>p!==position):[...prev.villainPositions,position];const villainStacks={...prev.villainStacks};const villainActions={...prev.villainActions};const villainActionAmounts={...prev.villainActionAmounts};if(exists){delete villainStacks[position];delete villainActions[position];delete villainActionAmounts[position]}return{...prev,villainPositions,villainStacks,villainActions,villainActionAmounts}});changed()}
  function setVillainStack(position:Position,value:string){setInput(prev=>({...prev,villainStacks:{...prev.villainStacks,[position]:numberOrNull(value)??undefined}}));changed()}
  function setVillainAction(position:Position,action:HandAction){setInput(prev=>{const current=prev.villainActions[position];const next=current===action?undefined:action;return{...prev,villainActions:{...prev.villainActions,[position]:next},villainActionAmounts:{...prev.villainActionAmounts,...(!next||!actionNeedsAmount(next)?{[position]:undefined}:{})}}});changed()}
  function setVillainActionAmount(position:Position,value:string){setInput(prev=>({...prev,villainActionAmounts:{...prev.villainActionAmounts,[position]:numberOrNull(value)??undefined}}));changed()}
  function setHeroAction(action:HandAction){setInput(prev=>{const next=prev.heroAction===action?null:action;return{...prev,heroAction:next,heroActionAmount:next&&actionNeedsAmount(next)?prev.heroActionAmount:null}});changed()}
  function setStreet(street:Street){const count=requiredBoardCards(street);setInput(prev=>({...prev,street,board:prev.board.slice(0,count)}));changed()}
  function openPicker(kind:"hero"|"board",index:number){setPicker({kind,index});setPickRank(null);setPickSuit(null)}
  function selectRank(rank:Rank){if(pickRank===rank){setPickRank(null);return}setPickRank(rank);if(pickSuit)commitCard(rank,pickSuit)}
  function selectSuit(suit:Suit){if(pickSuit===suit){setPickSuit(null);return}setPickSuit(suit);if(pickRank)commitCard(pickRank,suit)}
  function commitCard(rank:Rank,suit:Suit){
    if(!picker)return;const target=picker;const card=`${rank}${suit}` as Card;
    setInput(prev=>{const used=[...prev.heroCards,...prev.board];const source=target.kind==="hero"?prev.heroCards:prev.board;const current=source[target.index];if(used.includes(card)&&current!==card)return prev;const list=[...source];list[target.index]=card;return target.kind==="hero"?{...prev,heroCards:list as Card[]}:{...prev,board:list as Card[]}});
    changed();setPicker(null);setPickRank(null);setPickSuit(null);
  }
  function clearCard(){if(!picker)return;const target=picker;setInput(prev=>{const source=target.kind==="hero"?prev.heroCards:prev.board;const list=[...source];list.splice(target.index,1);return target.kind==="hero"?{...prev,heroCards:list as Card[]}:{...prev,board:list as Card[]}});setPicker(null);setPickRank(null);setPickSuit(null);changed()}
  async function analyze(){
    const current=validateHandReview(input);setSubmitted(true);if(!current.valid)return;
    setAiBusy(true);setAiAnswer("");setAiFallback(false);
    try{
      const response=await fetch("/api/poker-ai",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({question:handReviewPrompt(input)})});
      const data=await response.json() as {answer?:string;error?:string};
      if(!response.ok||!data.answer)throw new Error(data.error||"AI_TEMPORARILY_UNAVAILABLE");
      setAiAnswer(data.answer);
    }catch{
      setAiAnswer(localHandReview(input));setAiFallback(true);
    }finally{
      setAiBusy(false);window.scrollTo({top:0,behavior:"smooth"});
    }
  }
  function reset(){setInput(emptyInput);setSubmitted(false);setPicker(null);setPickRank(null);setPickSuit(null);setVisionDraft(null);setVisionError("");setVisionFile(null);setAiAnswer("");setAiFallback(false);if(visionPreview)URL.revokeObjectURL(visionPreview);setVisionPreview("")}

  function chooseVisionFile(file:File|null){if(!file)return;if(!["image/jpeg","image/png","image/webp"].includes(file.type)){setVisionError("USE JPG, PNG OU WEBP.");return}if(file.size>8*1024*1024){setVisionError("A IMAGEM DEVE TER NO MÁXIMO 8 MB.");return}if(visionPreview)URL.revokeObjectURL(visionPreview);setVisionFile(file);setVisionPreview(URL.createObjectURL(file));setVisionDraft(null);setVisionError("")}
  async function extractVision(){if(!visionFile||visionBusy)return;setVisionBusy(true);setVisionError("");setVisionDraft(null);try{const form=new FormData();form.set("image",visionFile);form.set("mode","HAND_REVIEW");form.set("question",visionContext.trim());const response=await fetch("/api/poker-vision",{method:"POST",body:form});const data=await response.json() as {draft?:VisionHandDraft;error?:string};if(!response.ok||!data.draft)throw new Error(data.error||"VISION_TEMPORARILY_UNAVAILABLE");setVisionDraft(data.draft)}catch(error){const code=error instanceof Error?error.message:"VISION_TEMPORARILY_UNAVAILABLE";setVisionError(code==="VISION_PARSE_FAILED"?"A IA NÃO CONSEGUIU ESTRUTURAR ESTA IMAGEM. TENTE OUTRO PRINT OU FOTO MAIS NÍTIDA.":code==="DAILY_LIMIT"||code==="MONTHLY_CREDITS"?"LIMITE DO STACKUP AI ATINGIDO.":"NÃO FOI POSSÍVEL LER A IMAGEM AGORA.")}finally{setVisionBusy(false)}}
  function applyVisionDraft(){if(!visionDraft)return;setInput(prev=>{const villainPositions=visionDraft.villains.length?visionDraft.villains.map(v=>v.position).filter(p=>p!==visionDraft.heroPosition):prev.villainPositions;const villainStacks={...prev.villainStacks};const villainActions={...prev.villainActions};const villainActionAmounts={...prev.villainActionAmounts};visionDraft.villains.forEach(v=>{if(v.position===visionDraft.heroPosition)return;if(v.stack!==null)villainStacks[v.position]=v.stack;if(v.action)villainActions[v.position]=v.action;if(v.actionAmount!==null)villainActionAmounts[v.position]=v.actionAmount});const visionNote=[visionDraft.notes,visionDraft.needsConfirmation.length?`CONFIRMAR: ${visionDraft.needsConfirmation.join(" · ")}`:""].filter(Boolean).join(" | ");return{...prev,game:visionDraft.game??prev.game,tournamentTypes:visionDraft.tournamentTypes.length?visionDraft.tournamentTypes:prev.tournamentTypes,tournamentPhase:visionDraft.tournamentPhase??prev.tournamentPhase,fieldLeft:visionDraft.fieldLeft??prev.fieldLeft,tableSize:visionDraft.tableSize??prev.tableSize,bigBlind:visionDraft.bigBlind??prev.bigBlind,ante:visionDraft.ante??prev.ante,pot:visionDraft.pot??prev.pot,street:visionDraft.street??prev.street,heroPosition:visionDraft.heroPosition??prev.heroPosition,heroCards:visionDraft.heroCards.length?visionDraft.heroCards:prev.heroCards,heroStack:visionDraft.heroStack??prev.heroStack,heroAction:visionDraft.heroAction??prev.heroAction,heroActionAmount:visionDraft.heroActionAmount??prev.heroActionAmount,board:visionDraft.board.length?visionDraft.board:prev.board,villainPositions,villainStacks,villainActions,villainActionAmounts,notes:visionNote?[prev.notes,`STACKUP VISION (${visionDraft.confidence}): ${visionNote}`].filter(Boolean).join("\n"):prev.notes}});changed();setVisionDraft(null)}

  if(submitted&&validation?.valid)return <Analysis input={input} commentary={aiAnswer} loading={aiBusy} fallback={aiFallback} onBack={()=>setSubmitted(false)} onReset={reset}/>;
  return <div className={styles.workspace}>
    <header className={styles.intro}><div className="eyebrow">AI HAND REVIEW</div><h2>MONTE A MÃO</h2><p>PREENCHA NA ORDEM EM QUE A MÃO ACONTECEU. OS CÁLCULOS SÃO ATUALIZADOS SEM DUPLICAR CONTRIBUIÇÕES NO POTE.</p></header>
    <section style={{display:"grid",gap:12}}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",flexWrap:"wrap"}}><div><div className="eyebrow">STACKUP AI VISION</div><h3 style={{margin:"5px 0 4px"}}>PREENCHER A PARTIR DE FOTO / PRINT</h3><p style={{margin:0,opacity:.72,fontSize:12}}>A IA extrai os dados. Você confirma antes de analisar.</p></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button type="button" className={styles.choice} onClick={()=>cameraRef.current?.click()}>CÂMERA</button><button type="button" className={styles.choice} onClick={()=>galleryRef.current?.click()}>ANEXAR IMAGEM</button></div></div><input ref={cameraRef} hidden type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={e=>chooseVisionFile(e.target.files?.[0]||null)}/><input ref={galleryRef} hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>chooseVisionFile(e.target.files?.[0]||null)}/>{visionFile&&<div style={{display:"grid",gridTemplateColumns:"110px 1fr",gap:12,marginTop:14,alignItems:"stretch"}}><img src={visionPreview} alt="Imagem para leitura" style={{width:110,height:110,objectFit:"cover",borderRadius:10,border:"1px solid rgba(92,187,126,.22)"}}/><div style={{display:"flex",flexDirection:"column",gap:8}}><textarea value={visionContext} onChange={e=>setVisionContext(e.target.value)} placeholder="CONTEXTO OPCIONAL" style={{minHeight:64}}/><button type="button" className="primary" onClick={()=>void extractVision()} disabled={visionBusy}>{visionBusy?"LENDO IMAGEM...":"IDENTIFICAR E PREENCHER"}</button></div></div>}{visionError&&<div className={styles.validation} style={{marginTop:12}}><strong>{visionError}</strong></div>}{visionDraft&&<div style={{marginTop:14,borderTop:"1px solid rgba(92,187,126,.18)",paddingTop:14}}><strong>LEITURA VISUAL · CONFIANÇA {visionDraft.confidence}</strong>{visionDraft.needsConfirmation.length>0&&<p style={{fontSize:12}}>CONFIRMAR: {visionDraft.needsConfirmation.join(" · ")}</p>}<button type="button" className="primary" onClick={applyVisionDraft}>APLICAR NOS CAMPOS</button></div>}</section>
    <Step n="01" title="CONTEXTO DO JOGO"><Section title="MODALIDADE"><div className={styles.two}>{(["CASH","TORNEIO"] as HandGameMode[]).map(game=><Choice key={game} active={input.game===game} onClick={()=>setGame(game)}>{game}</Choice>)}</div></Section>{input.game==="TORNEIO"&&<div className={styles.stepGrid}><Section title="TIPO" helper="1 OU MAIS"><div className={styles.grid}>{tournamentTypes.map(type=><Choice key={type} active={input.tournamentTypes.includes(type)} onClick={()=>toggleTournamentType(type)}>{type}</Choice>)}</div></Section><Section title="FASE"><div className={styles.grid}>{tournamentPhases.map(phase=><Choice key={phase} active={input.tournamentPhase===phase} onClick={()=>toggleNullable("tournamentPhase",phase as TournamentPhase)}>{phase}</Choice>)}</div></Section><Section title="FIELD LEFT"><div className={styles.four}>{fieldLeftOptions.map(value=><Choice key={value} active={input.fieldLeft===value} onClick={()=>toggleNullable("fieldLeft",value as FieldLeft)}>{value}</Choice>)}</div></Section></div>}<Section title="JOGADORES POR MESA"><div className={styles.five}>{tableSizes.map(size=><Choice key={size} active={input.tableSize===size} onClick={()=>toggleNullable("tableSize",size as TableSize)}>{size}</Choice>)}</div></Section></Step>
    <Step n="02" title="BLINDS, ANTE E STACKS"><div className={styles.moneyGrid}><MoneyField label="VALOR DO BB" value={input.bigBlind} onChange={v=>patch("bigBlind",numberOrNull(v))}/><MoneyField label="VALOR DO ANTE" value={input.ante} allowZero onChange={v=>patch("ante",numberOrZero(v))}/></div><Section title="POSIÇÃO · HERÓI"><div className={styles.positionGrid}>{positions.map(position=><Choice key={position} active={input.heroPosition===position} onClick={()=>selectHeroPosition(position)}>{position}</Choice>)}</div></Section><Section title="POSIÇÕES · VILÕES" helper="1 OU MAIS"><div className={styles.positionGrid}>{positions.map(position=><Choice key={position} active={input.villainPositions.includes(position)} disabled={input.heroPosition===position} onClick={()=>toggleVillain(position)}>{position}</Choice>)}</div></Section><Section title="STACKS"><StackRow label="HERÓI" value={input.heroStack} bigBlind={input.bigBlind} onChange={value=>patch("heroStack",numberOrNull(value))}/>{input.villainPositions.map(position=><StackRow key={position} label={position} value={input.villainStacks[position]??null} bigBlind={input.bigBlind} onChange={value=>setVillainStack(position,value)}/>)}</Section></Step>
    <Step n="03" title="POTE E STREET"><Section title="POT ANTES DAS AÇÕES"><MoneyField label="VALOR EM FICHAS" value={input.pot} bigBlind={input.bigBlind} onChange={v=>patch("pot",numberOrZero(v))}/></Section><Section title="STREET"><div className={styles.four}>{streets.map(street=><Choice key={street} active={input.street===street} onClick={()=>setStreet(street)}>{street}</Choice>)}</div></Section><Section title="BOARD"><div className={styles.cards}>{Array.from({length:5},(_,index)=><CardSlot key={index} card={input.board[index]} onClick={()=>openPicker("board",index)}/>)}</div></Section></Step>
    <Step n="04" title="AÇÕES DOS VILÕES"><Section title="SEQUÊNCIA INFORMADA">{input.villainPositions.map(position=><div className={styles.actionRow} key={position}><span className={styles.badge}>{position}</span><div><div className={styles.actionGrid}>{actions.filter(action=>action!=="FOLD").map(action=><Choice key={action} active={input.villainActions[position]===action} onClick={()=>setVillainAction(position,action)}>{action}</Choice>)}</div>{actionNeedsAmount(input.villainActions[position])&&<ActionAmount value={input.villainActionAmounts[position]??null} bigBlind={input.bigBlind} onChange={value=>setVillainActionAmount(position,value)}/>}</div></div>)}</Section></Step>
    <Step n="05" title="HERÓI E DECISÃO"><Section title="HERÓI · MÃO"><div className={styles.heroCards}>{[0,1].map(index=><CardSlot key={index} card={input.heroCards[index]} onClick={()=>openPicker("hero",index)}/>)}</div><h4 className={styles.subhead}>SUA AÇÃO</h4><div className={styles.actionGrid}>{actions.map(action=><Choice key={action} active={input.heroAction===action} onClick={()=>setHeroAction(action)}>{action}</Choice>)}</div>{actionNeedsAmount(input.heroAction)&&<ActionAmount value={input.heroActionAmount} bigBlind={input.bigBlind} onChange={value=>patch("heroActionAmount",numberOrNull(value))}/>}</Section><div className={styles.liveMath}><Metric label="POT ANTES DA AÇÃO DO HERÓI" value={`${math.potBeforeHeroAction.toLocaleString("pt-BR")} · ${formatBB(math.potBeforeHeroAction,input.bigBlind)}`}/><Metric label="POT APÓS AÇÕES" value={`${math.potAfterActions.toLocaleString("pt-BR")} · ${formatBB(math.potAfterActions,input.bigBlind)}`}/><Metric label="POT ODDS" value={math.potOdds!==null?`${trim(math.potOdds)}% · EXACT`:"NÃO SE APLICA / AGUARDANDO CALL"}/><Metric label="SPR" value={math.spr!==null?`${trim(math.spr)} · EXACT`:"DADOS INSUFICIENTES"}/></div></Step>
    <Step n="06" title="OBSERVAÇÕES"><Section title="OUTRAS INFORMAÇÕES"><textarea className={styles.notes} value={input.notes} onChange={e=>patch("notes",e.target.value)} placeholder="Reads, dinâmica, payout, bounty, histórico do vilão e outras informações relevantes..."/></Section></Step>
    {submitted&&validation&&!validation.valid&&<div className={styles.validation}><strong>INFORMAÇÕES INCOMPLETAS</strong>{validation.missing.length>0&&<p>{validation.missing.join(" · ")}</p>}{validation.conflicts.length>0&&<p>{validation.conflicts.join(" · ")}</p>}</div>}
    <button type="button" className="primary" onClick={analyze}>ANÁLISE E COMENTÁRIOS</button>
    {picker&&<div className={styles.modalBackdrop} onClick={()=>setPicker(null)}><div className={styles.modal} onClick={e=>e.stopPropagation()}><div className={styles.modalHead}><strong>SELECIONE A CARTA</strong><button type="button" onClick={()=>setPicker(null)}>×</button></div><div className={styles.rankGrid}>{ranks.map(rank=><Choice key={rank} active={pickRank===rank} onClick={()=>selectRank(rank)}>{rank}</Choice>)}</div><div className={styles.suitGrid}>{suits.map(suit=><Choice key={suit} active={pickSuit===suit} onClick={()=>selectSuit(suit)}>{suit}</Choice>)}</div><button type="button" className={styles.clear} onClick={clearCard}>LIMPAR CARTA</button></div></div>}
  </div>;
}

function hasStraight(cards:Card[]){
  const values=new Set(cards.map(card=>"23456789TJQKA".indexOf(card[0])+2));if(values.has(14))values.add(1);
  const sorted=[...values].sort((a,b)=>a-b);let run=1;for(let index=1;index<sorted.length;index++){run=sorted[index]===sorted[index-1]+1?run+1:1;if(run>=5)return true}return false;
}
function hasFlush(cards:Card[]){const suits=new Map<string,number>();cards.forEach(card=>suits.set(card.slice(-1),(suits.get(card.slice(-1))??0)+1));return [...suits.values()].some(count=>count>=5)}
function drawMath(input:HandReviewInput){
  const known=[...input.heroCards,...input.board].filter(Boolean) as Card[];if(input.street==="PREFLOP"||input.street==="RIVER"||known.length<5)return null;
  const ranks="23456789TJQKA".split("");const suits=["♠","♥","♦","♣"];const unseen=ranks.flatMap(rank=>suits.map(suit=>`${rank}${suit}` as Card)).filter(card=>!known.includes(card));
  const madeStraight=hasStraight(known),madeFlush=hasFlush(known);let straightOuts=0,flushOuts=0,totalOuts=0;
  unseen.forEach(card=>{const next=[...known,card];const straight=!madeStraight&&hasStraight(next);const flush=!madeFlush&&hasFlush(next);if(straight)straightOuts++;if(flush)flushOuts++;if(straight||flush)totalOuts++});
  if(totalOuts===0)return null;const cardsToCome=input.street==="FLOP"?2:1;const deckSize=52-known.length;const nextCard=totalOuts/deckSize*100;const byRiver=cardsToCome===2?(1-((deckSize-totalOuts)/deckSize)*((deckSize-1-totalOuts)/(deckSize-1)))*100:nextCard;
  return{outsBrutos:totalOuts,outsFlush:flushOuts,outsSequencia:straightOuts,probabilidadeProximaCartaPct:Number(nextCard.toFixed(2)),probabilidadeAteRiverPct:Number(byRiver.toFixed(2)),aviso:"Outs brutos; cartas dominadas ou que completam mãos melhores podem reduzir os outs limpos."};
}
function advancedHandMath(input:HandReviewInput){
  const math=calculateHandMath(input);const wager=Math.max(0,...input.villainPositions.map(position=>input.villainActionAmounts[position]??0));const potBeforeWager=Math.max(0,math.potBeforeHeroAction-wager);const heroRisk=Math.max(0,input.heroActionAmount??0);const effective=math.effectiveStack??0;const draws=drawMath(input);
  const alpha=wager>0&&potBeforeWager+wager>0?wager/(potBeforeWager+wager)*100:null;const mdf=alpha!==null?100-alpha:null;const price=math.heroCallCost&&math.heroCallCost>0?math.potBeforeHeroAction/math.heroCallCost:null;const sizingPct=heroRisk>0&&math.potBeforeHeroAction>0?heroRisk/math.potBeforeHeroAction*100:null;const foldEquityNeeded=heroRisk>0&&math.potBeforeHeroAction+heroRisk>0?heroRisk/(math.potBeforeHeroAction+heroRisk)*100:null;const stackRiskPct=heroRisk>0&&effective>0?heroRisk/effective*100:null;
  const hitChance=draws?(input.street==="FLOP"?draws.probabilidadeAteRiverPct:draws.probabilidadeProximaCartaPct)/100:null;const impliedNeeded=hitChance&&math.heroCallCost!==null?Math.max(0,math.heroCallCost/hitChance-(math.potBeforeHeroAction+math.heroCallCost)):null;
  return{spr:math.spr,potOddsPct:math.potOdds,equityMinimaPct:math.equityRequired,precoPotParaCall:price!==null?`${Number(price.toFixed(2))}:1`:null,apostaAdversaria:wager,apostaAdversariaPctPot:wager>0&&potBeforeWager>0?Number((wager/potBeforeWager*100).toFixed(2)):null,alphaPct:alpha!==null?Number(alpha.toFixed(2)):null,mdfPct:mdf!==null?Number(mdf.toFixed(2)):null,sizingHeroiPctPot:sizingPct!==null?Number(sizingPct.toFixed(2)):null,foldEquityMinimaPct:foldEquityNeeded!==null?Number(foldEquityNeeded.toFixed(2)):null,percentualStackArriscado:stackRiskPct!==null?Number(stackRiskPct.toFixed(2)):null,stackEfetivoBB:math.effectiveStackBB,outs:draws,ganhoFuturoMinimoImpliedOdds:impliedNeeded!==null?Number(impliedNeeded.toFixed(2)):null};
}

function handReviewPrompt(input:HandReviewInput){
  const summary=handReviewSummary(input);const math=summary.math;
  return `Atue como um coach de poker multicampeão ensinando um jogador recreativo que quer evoluir. Reúna em uma única análise coerente leitura de ranges e dinâmica de mesa, controle de pressão, identificação de erros exploráveis, experiência em torneios e rigor técnico baseado em teoria dos jogos. Não cite jogadores profissionais, programas, ferramentas ou solvers no texto final.

Comente especificamente a ação do herói nesta mão, com respeito, clareza e segurança, sem linguagem acadêmica desnecessária. Use fundamentos modernos de estratégia equilibrada e exploração, mas não invente outputs, frequências ou precisão inexistentes.

Escreva como uma pequena aula particular, curta, direta, didática e encadeada — não transforme critérios em uma lista de métricas. A primeira frase deve ser obrigatoriamente uma destas: "SUA AÇÃO FOI ÓTIMA.", "SUA AÇÃO FOI BOA." ou "SUA AÇÃO FOI RUIM." Escolha uma delas com base na conclusão mais provável, sem adiar o julgamento para o final.

Depois, organize o texto com começo, desenvolvimento e conclusão. No começo, apresente em poucas palavras a situação e a principal razão do julgamento. No desenvolvimento, explique por que a mão ou o range do herói funciona ou falha contra o range provável do adversário, considerando posição, stacks, pote, sizing, board e sequência. Sempre identifique ranges não informados como estimativas. Use conceitos de poker somente para sustentar o argumento, traduzindo cada termo técnico na própria frase. Use a matemática para mostrar pot odds, equity necessária, equity estimada, diferença percentual e EV em fichas e BB quando calculáveis.

Os dados incluem várias métricas pré-calculadas. Selecione apenas as que realmente influenciam este spot e use-as como evidência dentro do argumento. SPR, alpha, MDF, odds, outs, chance de completar draws, implied odds, fold equity mínima e percentual do stack arriscado não devem aparecer como inventário: cada número citado precisa explicar por que a ação foi boa ou ruim.

Faça uma estimativa realista do range adversário e da equity apenas quando os dados permitirem, identificando-a claramente como ESTIMATIVA. Compare-a com a equity mínima e calcule o EV da ação em fichas e BB. Mostre a projeção por 100 repetições iguais. Para apostas ou raises, declare as hipóteses de fold equity utilizadas. Se faltar informação indispensável, apresente um intervalo ou cenário de equilíbrio em vez de fabricar certeza.

Na conclusão, retome o julgamento inicial e mostre se repetir essa ação tende a dar lucro ou prejuízo. Apresente uma projeção por 100 decisões equivalentes e deixe claro o que é cálculo e o que é estimativa. Termine com uma única regra prática que o jogador possa lembrar e aplicar em mãos parecidas. Não cite sites, não repita os dados em blocos e não entregue apenas definições ou números soltos. O jogador deve terminar a leitura entendendo o motivo da decisão, não apenas sabendo o resultado.

DADOS DA MÃO:
${JSON.stringify({modalidade:summary.modality,mesa:summary.table,blindsAnte:summary.blinds,heroi:summary.hero,viloes:summary.villains,street:summary.street,board:summary.board,acaoHeroi:summary.heroAction,acoesViloes:input.villainPositions.map(position=>({posicao:position,stack:input.villainStacks[position],acao:input.villainActions[position],valor:input.villainActionAmounts[position]})),potInicial:math.basePot,potAntesHeroi:math.potBeforeHeroAction,potAposAcoes:math.potAfterActions,metricasCalculadas:advancedHandMath(input),observacoes:input.notes},null,2)}`;
}

function localHandReview(input:HandReviewInput){
  const summary=handReviewSummary(input);const math=summary.math;const action=input.heroAction??"AÇÃO NÃO INFORMADA";
  const advanced=advancedHandMath(input);
  const allIn=assessPreflopAllIn(input);
  const odds=math.potOdds!==null?`${trim(math.potOdds)}%`:null;
  const pressure=math.spr!==null&&math.spr<=2?"O SPR baixo aumenta o peso das decisões por todas as fichas.":math.spr!==null&&math.spr>=6?"O SPR alto exige mais cautela com mãos de força média.":"O SPR indica um compromisso intermediário com o pote.";
  const decision=action==="CALL"&&math.potOdds!==null
    ?(math.potOdds>50?`O CALL exige ${odds} de equity, um requisito muito alto. Sem evidência de que a mão supera essa frequência contra o range adversário, o FOLD tende a ser a alternativa mais disciplinada.`:`O CALL precisa de ao menos ${odds} de equity. Ele só é justificável se a mão alcançar essa participação contra o range que realizou a ação.`)
    :action==="FOLD"?"O FOLD preserva o stack, mas sua qualidade depende de a mão não possuir equity ou valor de showdown suficientes contra o range adversário."
    :["RAISE","3-BET","4-BET","ALL-IN"].includes(action)?`A ação ${action} é agressiva e precisa combinar valor suficiente com fold equity. O tamanho escolhido deve ser confrontado com o stack efetivo e com as mãos piores que continuam.`
    :`A ação ${action} deve ser comparada com alternativas passivas e agressivas, considerando posição, iniciativa e capacidade de extrair valor ou gerar folds.`;
  const totalAtCall=math.potBeforeHeroAction+(math.heroCallCost??0);const swingPerPoint=totalAtCall*.01;const swingBB=input.bigBlind?swingPerPoint/input.bigBlind:null;
  const sensitivity=input.heroAction==="CALL"&&math.potOdds!==null?`No ponto de equilíbrio, ${odds} de equity gera EV zero. Cada 1 ponto percentual acima ou abaixo disso altera o resultado em aproximadamente ${trim(swingPerPoint)} fichas${swingBB!==null?` (${trim(swingBB)} BB)`:""} por decisão; em 100 situações iguais, a diferença acumulada seria cerca de ${trim(swingPerPoint*100)} fichas para cada ponto percentual de vantagem ou desvantagem.`:"Sem uma estimativa de equity ou fold equity, não é responsável atribuir um lucro exato à ação.";
  if(allIn.applies&&allIn.estimatedEquity!==null&&allIn.requiredEquity!==null&&allIn.margin!==null&&math.heroCallCost!==null){
    const equity=allIn.estimatedEquity/100;const ev=equity*totalAtCall-math.heroCallCost;const evBB=input.bigBlind?ev/input.bigBlind:null;const projected=ev*100;
    const verdict=allIn.classification==="DECISÃO CORRETA"?(allIn.margin>=8?"ÓTIMA":"BOA"):"RUIM";
    const rangeText=allIn.estimatedJamRange!==null?`contra um range estimado de shove de aproximadamente ${trim(allIn.estimatedJamRange)}% das mãos`:"contra o range provável de shove";
    const supporting=[advanced.spr!==null?`O SPR era ${trim(advanced.spr)}, mostrando quanto do stack efetivo ainda existia em relação ao pote.`:null,advanced.precoPotParaCall?`O pote oferecia ${advanced.precoPotParaCall} para o call.`:null,advanced.percentualStackArriscado!==null?`A decisão colocava ${trim(advanced.percentualStackArriscado)}% do stack efetivo em risco.`:null,advanced.mdfPct!==null?`Contra esse tamanho, a frequência mínima de defesa teórica era ${trim(advanced.mdfPct)}%, mas isso não obriga esta combinação específica a pagar.`:null].filter(Boolean).join(" ");
    return `SUA AÇÃO FOI ${verdict}.\n\n${allIn.handClass} tem equity estimada de ${trim(allIn.estimatedEquity)}% ${rangeText}, enquanto o preço do pote exige ${trim(allIn.requiredEquity)}%. Em outras palavras, sua mão ficou ${trim(Math.abs(allIn.margin))} pontos percentuais ${allIn.margin>=0?"acima":"abaixo"} do necessário para o ${action} se pagar. ${supporting}\n\nO ${action} ${allIn.margin>=0?"supera":"não alcança"} o ponto de equilíbrio. O EV estimado é de ${ev>=0?"+":""}${trim(ev)} fichas${evBB!==null?` (${evBB>=0?"+":""}${trim(evBB)} BB)`:""} por decisão. Isso não significa que você vencerá esta mão específica; significa que a escolha ${ev>=0?"ganha":"perde"} fichas quando repetida muitas vezes contra esse mesmo tipo de range.\n\nEm 100 decisões equivalentes, a projeção é de ${projected>=0?"lucro":"prejuízo"} de aproximadamente ${trim(Math.abs(projected))} fichas. ${allIn.margin>=0?"Você pagou um preço menor do que a participação estimada da sua mão no pote, por isso a decisão tende a ser lucrativa.":"Você investiu mais do que sua chance estimada de vitória justificava; mesmo ganhando ocasionalmente, a repetição tende a ser prejudicial."}\n\nCONCLUSÃO — SUA AÇÃO FOI ${verdict} E, NESTAS CONDIÇÕES, TENDE A SER ${ev>=0?"LUCRATIVA":"NÃO LUCRATIVA"} NO LONGO PRAZO.\n\nREGRA PARA LEVAR À MESA — Contra um all-in, pague apenas quando a equity estimada da sua mão superar a equity mínima exigida pelo pote.`;
  }
  const verdict=action==="CALL"&&math.potOdds!==null&&math.potOdds>50?"RUIM":action==="FOLD"?"BOA":"RUIM";
  const drawEvidence=advanced.outs?`Há ${advanced.outs.outsBrutos} outs brutos para flush ou sequência, cerca de ${trim(advanced.outs.probabilidadeProximaCartaPct)}% na próxima carta${input.street==="FLOP"?` e ${trim(advanced.outs.probabilidadeAteRiverPct)}% até o river`:""}. Esses outs precisam ser descontados quando também melhoram o range adversário.`:"";
  const sizingEvidence=advanced.sizingHeroiPctPot!==null?`O tamanho escolhido corresponde a ${trim(advanced.sizingHeroiPctPot)}% do pote e precisa gerar ao menos ${trim(advanced.foldEquityMinimaPct??0)}% de folds para um blefe puro empatar.`:"";
  return `SUA AÇÃO FOI ${verdict}.\n\n${summary.hero} enfrenta ${summary.villains} em ${summary.street}. ${pressure} ${decision} ${drawEvidence}\n\n${sizingEvidence} ${sensitivity} Uma jogada é lucrativa quando ganha ou economiza fichas com frequência suficiente para compensar as vezes em que falha. Sem ranges ou reads informados, o ponto de equilíbrio matemático é a referência mais honesta; uma porcentagem inventada criaria falsa precisão.\n\nCONCLUSÃO — SUA AÇÃO FOI ${verdict}, MAS O VALOR EXATO DE LUCRO OU PREJUÍZO DEPENDE DA EQUITY REAL CONTRA O RANGE ADVERSÁRIO.\n\nREGRA PARA LEVAR À MESA — Compare a equity provável da sua mão com a equity mínima exigida pelo pote antes de confirmar a ação.`;
}

function Analysis({input,commentary,loading,fallback,onBack,onReset}:{input:HandReviewInput;commentary:string;loading:boolean;fallback:boolean;onBack:()=>void;onReset:()=>void}){const summary=handReviewSummary(input);const math=summary.math;const potOddsText=math.potOdds!==null?`${trim(math.potOdds)}%`:"NÃO SE APLICA";const mathReason=input.heroAction==="CALL"&&math.potOdds!==null?`O CALL PRECISA DE PELO MENOS ${potOddsText} DE EQUITY PARA EMPATAR EM CHIP EV.`:`A DECISÃO É MOSTRADA COM O POTE RECONSTRUÍDO, STACK EFETIVO E SPR.`;return <div className={styles.workspace}><div className={styles.analysisHead}><button type="button" className={styles.back} onClick={onBack}>← MÃO</button><div><div className="eyebrow">AI HAND REVIEW</div><h2>ANÁLISE DA MÃO</h2></div></div><div className={styles.summary}>{Object.entries({MODALIDADE:summary.modality,MESA:summary.table,"BB / ANTE":summary.blinds,HERÓI:summary.hero,VILÕES:summary.villains,"POT INICIAL":`${math.basePot.toLocaleString("pt-BR")} · ${formatBB(math.basePot,input.bigBlind)}`,"POT APÓS AÇÕES":`${math.potAfterActions.toLocaleString("pt-BR")} · ${formatBB(math.potAfterActions,input.bigBlind)}`,STREET:summary.street,BOARD:summary.board,"AÇÃO DO HERÓI":summary.heroAction}).map(([label,value])=><div key={label}><small>{label}</small><strong>{value}</strong></div>)}</div><div className={styles.verdict}><small>VEREDITO MATEMÁTICO</small><strong>{mathReason}</strong></div><div className={styles.analysisGrid}><AnalysisCard title={loading?"ANALISANDO A DECISÃO...":fallback?"ANÁLISE ESTRATÉGICA LOCAL":"COMENTÁRIOS SOBRE A DECISÃO"} text={loading?"CRUZANDO POSIÇÕES, STACKS, AÇÕES, POTE, BOARD E POT ODDS.":commentary}/></div><div className={styles.metrics}><Metric label="STACK EFETIVO" value={math.effectiveStackBB!==null?`${trim(math.effectiveStackBB)} BB · EXACT`:"DADOS INSUFICIENTES"}/><Metric label="POT ODDS" value={math.potOdds!==null?`${trim(math.potOdds)}% · EXACT`:"NÃO SE APLICA"}/><Metric label="SPR" value={math.spr!==null?`${trim(math.spr)} · EXACT`:"DADOS INSUFICIENTES"}/></div><button type="button" className="primary" onClick={onReset}>NOVA MÃO</button></div>}
function Step({n,title,children}:{n:string;title:string;children:React.ReactNode}){return <div className={styles.step}><div className={styles.stepHead}><span>{n}</span><strong>{title}</strong></div>{children}</div>}
function Section({title,helper,children}:{title:string;helper?:string;children:React.ReactNode}){return <section className={styles.section}><div className={styles.sectionTitle}><h3>{title}</h3>{helper&&<small>{helper}</small>}</div>{children}</section>}
function Choice({active,disabled,onClick,children}:{active?:boolean;disabled?:boolean;onClick:()=>void;children:React.ReactNode}){return <button type="button" aria-pressed={active} className={`${styles.choice} ${active?styles.active:""}`} disabled={disabled} onClick={onClick}>{children}</button>}
function MoneyField({label,value,bigBlind,allowZero,onChange}:{label:string;value:number|null;bigBlind?:number|null;allowZero?:boolean;onChange:(value:string)=>void}){return <label className={styles.moneyField}><span>{label}</span><div><input type="number" min="0" step="1" inputMode="numeric" value={value??""} onChange={e=>onChange(e.target.value)} placeholder="FICHAS"/>{bigBlind&&<b>{formatBB(value,bigBlind)}</b>}</div>{allowZero&&<small>ZERO É ACEITO QUANDO NÃO HÁ ANTE.</small>}</label>}
function StackRow({label,value,bigBlind,onChange}:{label:string;value:number|null;bigBlind:number|null;onChange:(value:string)=>void}){return <div className={styles.stackRow}><span className={styles.badge}>{label}</span><div className={styles.inputWithBB}><input type="number" min="0" step="1" inputMode="numeric" value={value??""} onChange={e=>onChange(e.target.value)} placeholder="STACK EM FICHAS"/><b>{formatBB(value,bigBlind)}</b></div></div>}
function ActionAmount({value,bigBlind,onChange}:{value:number|null;bigBlind:number|null;onChange:(value:string)=>void}){return <div className={styles.actionAmount}><span>VALOR DA AÇÃO</span><div className={styles.inputWithBB}><input type="number" min="0" step="1" inputMode="numeric" value={value??""} onChange={e=>onChange(e.target.value)} placeholder="FICHAS"/><b>{formatBB(value,bigBlind)}</b></div></div>}
function CardSlot({card,disabled,onClick}:{card?:Card;disabled?:boolean;onClick:()=>void}){return <button type="button" className={styles.card} disabled={disabled} onClick={onClick}>{card??"+"}</button>}
function AnalysisCard({title,text}:{title:string;text:string}){return <div className={styles.analysisCard}><small>{title}</small><p>{text}</p></div>}
function Metric({label,value}:{label:string;value:string}){return <div className={styles.metric}><small>{label}</small><strong>{value}</strong></div>}
function numberOrNull(value:string){const parsed=Number(value);return Number.isFinite(parsed)&&parsed>0?parsed:null}
function numberOrZero(value:string){if(value.trim()==="")return null;const parsed=Number(value);return Number.isFinite(parsed)&&parsed>=0?parsed:null}
