import type {PlayerAction} from "@/data/player-dna-spots";
import type {SolverSpotState} from "@/lib/player-dna-solver-v2";
import {analyzeTechnicalDecision} from "@/lib/player-dna-technical-analysis";
import {inspectGtoNode} from "@/lib/gto-node-integrity";
import {evaluateCallFoldEv} from "@/lib/gto-call-ev";
import {exactMultiwayShowdownEquity} from "@/lib/gto-multiway-equity-engine";
import {buildExactPotAccounting} from "@/lib/gto-pot-accounting";
import {evaluateExactTerminalMultiwayEv} from "@/lib/gto-multiway-terminal-ev";

export type AdvancedVerdictCode="CORRECT_ACTION"|"ADJUSTABLE_ACTION"|"INCORRECT_ACTION"|"UNVALIDATED_ACTION";
export type AdvancedEvStatus="EV_MAX"|"EV_NEUTRAL"|"EV_NEGATIVE"|"UNVALIDATED";
export type AdvancedRangeAction={action_name:string;frequency_percent:number|null;ev_status:AdvancedEvStatus;note:string};
export type AdvancedStreetAnalysis={street:"Pre-Flop"|"Flop"|"Turn"|"River";decision_point:string;technical_evaluation:string;action_classification:{verdict_code:AdvancedVerdictCode;verdict_label:"Ação Correta (+EV)"|"Ação Ajustável (Mista)"|"Ação Incorreta (-EV)"|"Análise GTO não validada";justification:string};range_action_distribution:{total_percentage:100|null;actions:AdvancedRangeAction[]}};
export type AdvancedDecisionEvaluatorOutput={street_analysis:AdvancedStreetAnalysis[]};
const streetLabel:Record<SolverSpotState["street"],AdvancedStreetAnalysis["street"]>={PREFLOP:"Pre-Flop",FLOP:"Flop",TURN:"Turn",RIVER:"River"};
function actionLabel(action:PlayerAction,sizing?:string){return sizing&&["BET","RAISE"].includes(action)?`${action} ${sizing}`:action}
function pct(v:number|null){return v===null?"N/A":`${(v*100).toFixed(1)}%`}
function activeVillainCount(state:SolverSpotState){const hero=state.hero.position.toUpperCase();return state.players.filter(p=>p.position.toUpperCase()!==hero&&p.action.toUpperCase()!=="FOLD").length}
export function evaluateAdvancedDecision(state:SolverSpotState,selectedAction:PlayerAction,legalActions:PlayerAction[],selectedSizing?:string):AdvancedDecisionEvaluatorOutput{
 const integrity=inspectGtoNode(state,legalActions),legal=integrity.legalActions,selectedIsLegal=legal.includes(selectedAction),technical=analyzeTechnicalDecision(state,selectedAction,legal,selectedSizing),callFold=evaluateCallFoldEv(state),potAccounting=buildExactPotAccounting(state),villains=activeVillainCount(state),multiway=villains>1?exactMultiwayShowdownEquity(state):null,terminalMultiway=villains>1?evaluateExactTerminalMultiwayEv(state):null;
 const diagnosticVerdict:AdvancedVerdictCode=technical.verdict.startsWith("AÇÃO CORRETA")?"CORRECT_ACTION":technical.verdict.startsWith("AÇÃO INCORRETA")?"INCORRECT_ACTION":"ADJUSTABLE_ACTION";let verdictCode:AdvancedVerdictCode=!selectedIsLegal?"INCORRECT_ACTION":"UNVALIDATED_ACTION";let verdictLabel:AdvancedStreetAnalysis["action_classification"]["verdict_label"]=!selectedIsLegal?"Ação Incorreta (-EV)":"Análise GTO não validada",deterministicJustification="";
 if(selectedIsLegal&&callFold.status==="EXACT_TERMINAL"&&(selectedAction==="CALL"||selectedAction==="FOLD")){const callEv=callFold.callEvBb??0,preferred=callFold.preferred;if(preferred==="INDIFFERENT"){verdictCode="ADJUSTABLE_ACTION";verdictLabel="Ação Ajustável (Mista)"}else if(selectedAction===preferred){verdictCode="CORRECT_ACTION";verdictLabel="Ação Correta (+EV)"}else{verdictCode="INCORRECT_ACTION";verdictLabel="Ação Incorreta (-EV)"}deterministicJustification=`EV TERMINAL DETERMINÍSTICO CONTRA RANGE PONDERADO: EQUITY ${pct(callFold.equity)} · EQUITY NECESSÁRIA ${pct(callFold.requiredEquity)} · EV CALL ${callEv.toFixed(3)} BB · EV FOLD 0.000 BB · LINHA MATEMÁTICA ${preferred}. NÃO É FREQUÊNCIA GTO NEM SOLUÇÃO DE EQUILÍBRIO.`}
 const decisionPoint=selectedSizing?`HERO ESCOLHE ${selectedAction} ${selectedSizing}`:`HERO ESCOLHE ${selectedAction}`,treeAudit=`TO CALL ${integrity.toCall.toFixed(1)} BB · POT ${integrity.potBeforeCall.toFixed(1)} BB · POT ODDS ${pct(integrity.potOdds)} · STACK EFETIVO ${integrity.effectiveStack.toFixed(1)} BB · SPR ${integrity.spr===null?"N/A":integrity.spr.toFixed(2)} · ${integrity.facingBet?"ENFRENTA APOSTA/RAISE":"SEM APOSTA A ENFRENTAR"} · AÇÕES LEGAIS ${legal.join(", ")}`,readiness=`RANGES ${integrity.rangeReady?"OK":"AUSENTES"} · BLOCKERS ${integrity.blockersReady?"OK":"INVÁLIDOS"} · EQUITY ${integrity.equityReady?"ELEGÍVEL":"BLOQUEADA"} · POTS ${integrity.potAccountingReady?"EXATOS":"NÃO VALIDADOS"} · ICM ${integrity.icmReady?"OK":"INCOMPLETO"} · PRÉ-REQUISITOS ${integrity.solverReady?"OK":"INCOMPLETOS"}`,issues=integrity.issues.length?integrity.issues.join(" | "):"SEM INCONSISTÊNCIAS ESTRUTURAIS DETECTADAS";
 let potAudit="POT ACCOUNTING INDISPONÍVEL: COMMITMENTS TOTAIS NÃO FORNECIDOS";if(potAccounting.status==="OK"){const layers=potAccounting.pots.map((pot,index)=>`${index===0?"MAIN":`SIDE ${index}`} ${pot.amountBb.toFixed(2)} BB [${pot.eligible.join(", ")}]`).join(" · ");potAudit=`POT ACCOUNTING EXATO: ${layers||"SEM CAMADAS CONTESTADAS"} · TOTAL ${potAccounting.totalPotBb.toFixed(2)} BB${potAccounting.refunds.length?` · REFUNDS ${potAccounting.refunds.map(r=>`${r.position} ${r.amountBb.toFixed(2)} BB`).join(", ")}`:""}${potAccounting.reconciliationDeltaBb!==null?` · DELTA ${potAccounting.reconciliationDeltaBb.toFixed(2)} BB`:""}`}else if(potAccounting.issues.length)potAudit=`POT ACCOUNTING ${potAccounting.status}: ${potAccounting.issues.join(" / ")}`;
 let equityAudit="";if(terminalMultiway?.status==="OK"){const pots=terminalMultiway.pots.map(p=>`${p.index===0?"MAIN":`SIDE ${p.index}`} HERO SHARE ${pct(p.heroShare)}`).join(" · ");equityAudit=`EV TERMINAL MULTIWAY EXATO POR ELEGIBILIDADE DE POTE · RETORNO BRUTO HERO ${terminalMultiway.heroGrossReturnBb!.toFixed(3)} BB · COMMITMENT HERO ${terminalMultiway.heroCommittedBb!.toFixed(3)} BB · EV SHOWDOWN ${terminalMultiway.heroEvBb!.toFixed(3)} BB · ${pots} · ${terminalMultiway.states} TUPLAS. NÃO É EV DE UMA DECISÃO ANTERIOR NEM SOLUÇÃO GTO.`}else if(multiway){if(multiway.status==="OK"){const hero=multiway.players.find(p=>p.position.toUpperCase()===state.hero.position.toUpperCase()),villainSummary=multiway.players.filter(p=>p.position.toUpperCase()!==state.hero.position.toUpperCase()).map(p=>`${p.position.toUpperCase()} ${pct(p.equity)}`).join(" · ");equityAudit=`EQUITY MULTIWAY EXATA · HERO ${pct(hero?.equity??null)} · ${villainSummary}. EV DE AÇÃO BLOQUEADO SEM ÁRVORE TERMINAL EXATA.`}else equityAudit=`EQUITY MULTIWAY BLOQUEADA: ${multiway.issues.join(" / ")}`}else if(callFold.status==="EXACT_TERMINAL")equityAudit=`EV CALL/FOLD TERMINAL DISPONÍVEL · EQUITY ${pct(callFold.equity)} · REQUIRED ${pct(callFold.requiredEquity)} · CALL EV ${(callFold.callEvBb??0).toFixed(3)} BB`;else if(callFold.status==="EQUITY_ONLY")equityAudit=`EQUITY DE SHOWDOWN ${pct(callFold.equity)} DISPONÍVEL, MAS EV DE CALL NÃO É FECHADO POR EXISTIREM DECISÕES FUTURAS`;else equityAudit=`EV CALL/FOLD INDISPONÍVEL: ${callFold.issues.join(" / ")}`;
 const justification=!selectedIsLegal?`AÇÃO ${selectedAction} É ILEGAL NESTE NÓ. ${treeAudit}.`:deterministicJustification||`SEM SOLUÇÃO CONVERGIDA/VALIDADA, O APP NÃO ATRIBUI +EV/-EV GTO NEM FREQUÊNCIA GTO. O DIAGNÓSTICO INTERNO APONTA ${technical.bestAction} (${diagnosticVerdict}), APENAS COMO HIPÓTESE DE ESTUDO.`,distribution:AdvancedRangeAction[]=legal.map(action=>({action_name:actionLabel(action,action===selectedAction?selectedSizing:undefined),frequency_percent:null,ev_status:"UNVALIDATED",note:"FREQUÊNCIA E EV ESTRATÉGICO BLOQUEADOS ATÉ EXISTIR SOLUÇÃO GTO VALIDADA PARA ESTE NÓ."}));return{street_analysis:[{street:streetLabel[state.street],decision_point:decisionPoint,technical_evaluation:`INTEGRIDADE DO NÓ: ${treeAudit} | PRONTIDÃO: ${readiness} | POTS: ${potAudit} | EQUITY/EV: ${equityAudit} | PENDÊNCIAS: ${issues}`,action_classification:{verdict_code:verdictCode,verdict_label:verdictLabel,justification},range_action_distribution:{total_percentage:null,actions:distribution}}]}
}
