import type {SolverSpotState} from "@/lib/player-dna-solver-v2";
import {canonicalCard,normalizeWeightedRange,type WeightedCombo} from "@/lib/gto-range-engine";
import {bestHoldemScore} from "@/lib/gto-equity-engine";
import {buildExactPotAccounting} from "@/lib/gto-pot-accounting";

export type MultiwayTerminalEvResult={status:"OK"|"UNAVAILABLE"|"INVALID";heroEvBb:number|null;heroGrossReturnBb:number|null;heroCommittedBb:number|null;pots:{index:number;amountBb:number;eligible:string[];heroShare:number}[];weightedTrials:number;states:number;issues:string[]};
const RANKS="23456789TJQKA",SUITS=["S","H","D","C"] as const,DECK=[...RANKS].flatMap(r=>SUITS.map(s=>`${r}${s}`)),MAX_STATES=250000;
type Pick={position:string;cards:[string,string];weight:number};
const upper=(v:string)=>v.trim().toUpperCase();
function combinations<T>(xs:T[],k:number){const out:T[][]=[];const walk=(i:number,p:T[])=>{if(p.length===k){out.push(p);return}for(let j=i;j<=xs.length-(k-p.length);j++)walk(j+1,[...p,xs[j]])};walk(0,[]);return out}
function compare(a:number[],b:number[]){for(let i=0;i<Math.max(a.length,b.length);i++){const d=(a[i]??0)-(b[i]??0);if(d)return d>0?1:-1}return 0}
export function evaluateExactTerminalMultiwayEv(state:SolverSpotState):MultiwayTerminalEvResult{
 const accounting=buildExactPotAccounting(state),issues=[...accounting.issues],heroPos=upper(state.hero.position),heroCards=state.hero.cards.map(canonicalCard).filter(Boolean) as string[],board=state.board.map(canonicalCard).filter(Boolean) as string[];
 if(accounting.status!=="OK"||accounting.reconciliationDeltaBb===null||Math.abs(accounting.reconciliationDeltaBb)>.01)return{status:"UNAVAILABLE",heroEvBb:null,heroGrossReturnBb:null,heroCommittedBb:null,pots:[],weightedTrials:0,states:0,issues:[...issues,"POT ACCOUNTING EXATO É OBRIGATÓRIO PARA EV MULTIWAY."]};
 if(board.length!==5)return{status:"UNAVAILABLE",heroEvBb:null,heroGrossReturnBb:null,heroCommittedBb:null,pots:[],weightedTrials:0,states:0,issues:[...issues,"EV MULTIWAY TERMINAL ATUAL EXIGE RIVER COMPLETO."]};
 if(heroCards.length!==2||new Set([...heroCards,...board]).size!==7)return{status:"INVALID",heroEvBb:null,heroGrossReturnBb:null,heroCommittedBb:null,pots:[],weightedTrials:0,states:0,issues:[...issues,"CARTAS INVÁLIDAS/DUPLICADAS."]};
 const active=state.players.filter(p=>upper(p.position)!==heroPos&&upper(p.action)!=="FOLD"),visible=[...heroCards,...board],participants:{position:string;combos:WeightedCombo[]}[]=[];
 for(const p of active){const range=state.ranges?.villains?.[p.position]??Object.entries(state.ranges?.villains??{}).find(([x])=>upper(x)===upper(p.position))?.[1];if(!range?.length)return{status:"UNAVAILABLE",heroEvBb:null,heroGrossReturnBb:null,heroCommittedBb:null,pots:[],weightedTrials:0,states:0,issues:[...issues,`RANGE AUSENTE PARA ${upper(p.position)}.`]};const n=normalizeWeightedRange(range,visible);if(!n.combos.length)return{status:"UNAVAILABLE",heroEvBb:null,heroGrossReturnBb:null,heroCommittedBb:null,pots:[],weightedTrials:0,states:0,issues:[...issues,`RANGE DE ${upper(p.position)} SEM COMBOS VÁLIDOS.`]};participants.push({position:upper(p.position),combos:n.combos})}
 const upperStates=participants.reduce((n,p)=>n*p.combos.length,1);if(upperStates>MAX_STATES)return{status:"UNAVAILABLE",heroEvBb:null,heroGrossReturnBb:null,heroCommittedBb:null,pots:[],weightedTrials:0,states:0,issues:[...issues,`ESPAÇO EXATO EXCEDE ${MAX_STATES} ESTADOS; NÃO HÁ AMOSTRAGEM.`]};
 const shares=accounting.pots.map(p=>({index:p.index,amountBb:p.amountBb,eligible:p.eligible,weightedHeroShare:0}));let totalWeight=0,states=0;
 const walk=(i:number,picks:Pick[],dead:Set<string>,weight:number)=>{if(i===participants.length){states++;const score=new Map<string,number[]>();score.set(heroPos,bestHoldemScore([...heroCards,...board]));for(const p of picks)score.set(p.position,bestHoldemScore([...p.cards,...board]));for(const pot of shares){const eligible=pot.eligible.filter(pos=>score.has(upper(pos))).map(upper);if(!eligible.includes(heroPos))continue;let best=score.get(eligible[0])!;for(const pos of eligible){const s=score.get(pos)!;if(compare(s,best)>0)best=s}const winners=eligible.filter(pos=>compare(score.get(pos)!,best)===0);if(winners.includes(heroPos))pot.weightedHeroShare+=weight/winners.length}totalWeight+=weight;return}const p=participants[i];for(const c of p.combos){if(c.cards.some(x=>dead.has(x)))continue;const next=new Set(dead);c.cards.forEach(x=>next.add(x));walk(i+1,[...picks,{position:p.position,cards:c.cards,weight:c.weight}],next,weight*c.weight)}};
 walk(0,[],new Set(visible),1);if(totalWeight<=0)return{status:"UNAVAILABLE",heroEvBb:null,heroGrossReturnBb:null,heroCommittedBb:null,pots:[],weightedTrials:0,states,issues:[...issues,"NENHUMA TUPLA DE RANGES COMPATÍVEL."]};
 const pots=shares.map(p=>({index:p.index,amountBb:p.amountBb,eligible:p.eligible,heroShare:p.weightedHeroShare/totalWeight})),gross=pots.reduce((s,p)=>s+p.amountBb*p.heroShare,0),committed=Math.max(0,state.commitments?.[state.hero.position]??Object.entries(state.commitments??{}).find(([x])=>upper(x)===heroPos)?.[1]??0),ev=gross-committed;
 return{status:"OK",heroEvBb:ev,heroGrossReturnBb:gross,heroCommittedBb:committed,pots,weightedTrials:totalWeight,states,issues};
}
