import type {PlayerAction} from "@/data/player-dna-spots";
import type {SolverSpotState} from "@/lib/player-dna-solver-v2";

export type TechnicalActionMix={action:PlayerAction;frequency:number;classification:"MAIOR EV"|"MISTA"|"MENOR EV"};
export type TechnicalDecision={verdict:"AÇÃO CORRETA (+EV)"|"AÇÃO AJUSTÁVEL (MISTA / EV NEUTRO)"|"AÇÃO INCORRETA (-EV)";mix:TechnicalActionMix[];summary:string;handClass:string;estimatedEquity:number;potOdds:number;spr:number};
const rankValue:Record<string,number>={"2":2,"3":3,"4":4,"5":5,"6":6,"7":7,"8":8,"9":9,"T":10,"J":11,"Q":12,"K":13,"A":14};
function clamp(v:number,min=0,max=1){return Math.max(min,Math.min(max,v))}
function round(v:number,p=1){const f=10**p;return Math.round(v*f)/f}
function parseCard(card:string){const c=card.trim().toUpperCase();return{rank:c[0]??"2",suit:c.slice(1)}}
function combinations<T>(items:T[],k:number){const out:T[][]=[];const walk=(start:number,pick:T[])=>{if(pick.length===k){out.push(pick);return}for(let i=start;i<items.length;i++)walk(i+1,[...pick,items[i]])};walk(0,[]);return out}
function fiveCardRank(raw:{rank:string;suit:string}[]){const values=raw.map(c=>rankValue[c.rank]??2).sort((a,b)=>b-a);const counts=new Map<number,number>();values.forEach(v=>counts.set(v,(counts.get(v)??0)+1));const groups=[...counts.entries()].sort((a,b)=>b[1]-a[1]||b[0]-a[0]);const unique=[...new Set(values)];if(unique.includes(14))unique.push(1);let straightHigh=0;for(let high=14;high>=5;high--){if([0,1,2,3,4].every(d=>unique.includes(high-d))){straightHigh=high;break}}const flush=raw.every(c=>c.suit===raw[0].suit);if(flush&&straightHigh)return{cat:8,label:"STRAIGHT FLUSH",score:8e6+straightHigh};if(groups[0][1]===4)return{cat:7,label:"QUADRA",score:7e6+groups[0][0]*100+groups[1][0]};if(groups[0][1]===3&&groups[1][1]===2)return{cat:6,label:"FULL HOUSE",score:6e6+groups[0][0]*100+groups[1][0]};if(flush)return{cat:5,label:"FLUSH",score:5e6+values.reduce((s,v,i)=>s+v*10**(4-i),0)};if(straightHigh)return{cat:4,label:"SEQUÊNCIA",score:4e6+straightHigh};if(groups[0][1]===3)return{cat:3,label:"TRINCA",score:3e6+groups[0][0]*10000+groups.slice(1).map(x=>x[0]).sort((a,b)=>b-a).reduce((s,v,i)=>s+v*10**(1-i),0)};if(groups[0][1]===2&&groups[1][1]===2){const p=[groups[0][0],groups[1][0]].sort((a,b)=>b-a);return{cat:2,label:"DOIS PARES",score:2e6+p[0]*10000+p[1]*100+groups[2][0]}}if(groups[0][1]===2)return{cat:1,label:"PAR",score:1e6+groups[0][0]*10000};return{cat:0,label:"HIGH CARD",score:values.reduce((s,v,i)=>s+v*10**(4-i),0)}}
function postflopStrength(state:SolverSpotState){const all=[...state.hero.cards,...state.board].map(parseCard);if(all.length<5)return{strength:.2,label:"MÃO NÃO CLASSIFICADA",draw:false};const best=combinations(all,5).map(fiveCardRank).sort((a,b)=>b.score-a.score)[0];const boardOnly=state.board.length>=5?fiveCardRank(state.board.slice(0,5).map(parseCard)):null;let strength=[.18,.38,.60,.72,.80,.86,.92,.97,.99][best.cat]??.18;if(boardOnly&&boardOnly.cat===best.cat&&best.cat<=2)strength-=.09;const suits=new Map<string,number>();all.forEach(c=>suits.set(c.suit,(suits.get(c.suit)??0)+1));const flushDraw=[...suits.values()].some(v=>v===4)&&best.cat<5;return{strength:clamp(strength,.05,.99),label:best.label,draw:flushDraw}}
function preflopStrength(state:SolverSpotState){const h=state.hero.cards.map(parseCard);if(h.length<2)return{strength:.2,label:"MÃO NÃO CLASSIFICADA",draw:false};const a=rankValue[h[0].rank]??2,b=rankValue[h[1].rank]??2,hi=Math.max(a,b),lo=Math.min(a,b),pair=a===b,suited=h[0].suit===h[1].suit,gap=hi-lo;let s=.08+(hi-2)/12*.25+(lo-2)/12*.10;if(pair)s=.30+(hi-2)/12*.52;if(suited)s+=.035;if(gap===1)s+=.025;else if(gap===2)s+=.012;if(hi===14&&lo>=10)s+=.10;if(hi===13&&lo>=11)s+=.05;return{strength:clamp(s,.04,.95),label:pair?`${h[0].rank}${h[1].rank}`:`${h[0].rank}${h[1].rank}${suited?"S":"O"}`,draw:false}}
function math(state:SolverSpotState){const heroPos=state.hero.position.toUpperCase();const active=state.players.filter(p=>p.action.toUpperCase()!=="FOLD"&&p.position.toUpperCase()!==heroPos);const blind=state.street==="PREFLOP"?(heroPos==="SB"?.5:heroPos==="BB"?1:0):0;const maxCommit=Math.max(0,...state.players.filter(p=>p.action.toUpperCase()!=="FOLD").map(p=>p.value));const toCall=Math.max(0,state.heroToCall??(maxCommit-blind));const potOdds=toCall>0?toCall/(Math.max(0,state.pot)+toCall):0;const eff=Math.max(0,Math.min(state.hero.stack,...(active.length?active.map(p=>p.stack):[state.hero.stack])));return{toCall,potOdds,spr:state.pot>0?eff/state.pot:0,opponents:active.length,multiway:active.length>1}}
function rankLegal(scores:Record<string,number>,legal:PlayerAction[]){const uniq=[...new Set(legal)];const sorted=uniq.map(action=>({action,score:scores[action]??-99})).sort((a,b)=>b.score-a.score);const best=sorted[0]?.score??0,worst=sorted[sorted.length-1]?.score??0;return sorted.map((x,i)=>({action:x.action,frequency:i===0?100:0,classification:(Math.abs(x.score-best)<.08?"MAIOR EV":Math.abs(x.score-worst)<.08?"MENOR EV":"MISTA") as TechnicalActionMix["classification"]}))}
export function analyzeTechnicalDecision(state:SolverSpotState,selectedAction:PlayerAction,legalActions:PlayerAction[]):TechnicalDecision{
  const m=math(state),hand=state.street==="PREFLOP"?preflopStrength(state):postflopStrength(state),scenario=state.scenario.join(" ").toUpperCase();const icm=state.mode==="TORNEIO"&&(scenario.includes("ICM")||scenario.includes("BOLHA")||scenario.includes("FT"));let strength=hand.strength;
  if(m.opponents>1)strength*=Math.pow(.76,m.opponents-1);if(state.street==="PREFLOP"&&m.toCall>=8)strength-=.06;if(state.street==="PREFLOP"&&m.toCall>=12)strength-=.06;if(state.street==="PREFLOP"&&m.toCall>=20)strength-=.05;if(icm)strength-=.04;strength=clamp(strength,.02,.98);
  const margin=strength-m.potOdds,score:Record<string,number>={FOLD:-99,CHECK:-99,CALL:-99,BET:-99,RAISE:-99,"ALL-IN":-99};
  if(m.toCall>0){score.FOLD=.7-margin*4+(m.multiway?.35:0)+(icm?.2:0);score.CALL=.5+margin*5-(m.multiway?.28:0)-(m.toCall>=12?.12:0);score.RAISE=.15+strength*2.0-(m.multiway?.30:0)-(icm?.2:0);score["ALL-IN"]=-.05+strength*2.2+(m.spr<=1.5?.3:0)-(m.multiway?.35:0)-(icm?.35:0)}else{score.CHECK=.65+(1-strength)*.45;score.BET=.35+strength*1.8;score.RAISE=score.BET;score["ALL-IN"]=-.1+strength*2+(m.spr<=1?.35:0)}
  const mix=rankLegal(score,legalActions),chosenScore=score[selectedAction]??-99,bestScore=Math.max(...legalActions.map(a=>score[a]??-99));let verdict:TechnicalDecision["verdict"]="AÇÃO AJUSTÁVEL (MISTA / EV NEUTRO)";const gap=bestScore-chosenScore;if(gap<=.08)verdict="AÇÃO CORRETA (+EV)";else if(gap>=.55)verdict="AÇÃO INCORRETA (-EV)";
  const summary=`${hand.label} · FORÇA BASE ${round(strength*100,1)}% · POT ODDS ${round(m.potOdds*100,1)}% · SPR ${round(m.spr,2)}${icm?" · PRESSÃO ICM":""}${m.multiway?` · MULTIWAY ${m.opponents+1}-WAY`:""}`;
  return{verdict,mix,summary,handClass:hand.label,estimatedEquity:round(strength*100,1),potOdds:round(m.potOdds*100,1),spr:round(m.spr,2)};
}
