import type {PlayerAction} from "@/data/player-dna-spots";
import type {SolverSpotState} from "@/lib/player-dna-solver-v2";

export type TechnicalActionMix={action:PlayerAction;frequency:number;classification:"MAIOR EV"|"MISTA"|"MENOR EV"};
export type TechnicalDecision={verdict:"AÇÃO CORRETA (+EV)"|"AÇÃO AJUSTÁVEL (MISTA / EV NEUTRO)"|"AÇÃO INCORRETA (-EV)";mix:TechnicalActionMix[];summary:string;handClass:string;estimatedEquity:number;potOdds:number;spr:number};
const rankValue:Record<string,number>={"2":2,"3":3,"4":4,"5":5,"6":6,"7":7,"8":8,"9":9,"T":10,"J":11,"Q":12,"K":13,"A":14};
function clamp(v:number,min=0,max=1){return Math.max(min,Math.min(max,v))} function round(v:number,p=1){const f=10**p;return Math.round(v*f)/f} function parseCard(card:string){const c=card.trim().toUpperCase();return{rank:c[0]??"2",suit:c.slice(1)}}
function preflopStrength(state:SolverSpotState){const h=state.hero.cards.map(parseCard);if(h.length<2)return{strength:.2,label:"MÃO NÃO CLASSIFICADA",draw:false};const a=rankValue[h[0].rank]??2,b=rankValue[h[1].rank]??2,hi=Math.max(a,b),lo=Math.min(a,b),pair=a===b,suited=h[0].suit===h[1].suit,gap=hi-lo;let s=.10+(hi-2)/12*.24+(lo-2)/12*.10;if(pair)s=.32+(hi-2)/12*.50;if(suited)s+=.035;if(gap===1)s+=.025;if(hi===14&&lo>=10)s+=.11;if(hi===13&&lo>=11)s+=.055;return{strength:clamp(s,.05,.94),label:pair?`${h[0].rank}${h[1].rank}`:`${h[0].rank}${h[1].rank}${suited?"S":"O"}`,draw:false}}
function postflopStrength(state:SolverSpotState){const hero=state.hero.cards.map(parseCard),board=state.board.map(parseCard),all=[...hero,...board],vals=all.map(c=>rankValue[c.rank]??2),counts=new Map<number,number>();vals.forEach(v=>counts.set(v,(counts.get(v)??0)+1));const groups=[...counts.values()].sort((a,b)=>b-a);if(groups[0]>=4)return{strength:.97,label:"QUADRA",draw:false};if(groups[0]>=3&&groups[1]>=2)return{strength:.94,label:"FULL HOUSE",draw:false};if(groups[0]>=3)return{strength:.76,label:"TRINCA",draw:false};if(groups[0]===2&&groups[1]===2)return{strength:.66,label:"DOIS PARES",draw:false};if(groups[0]===2)return{strength:.48,label:"PAR",draw:false};const hi=Math.max(...hero.map(c=>rankValue[c.rank]??2));return{strength:.12+(hi-2)/12*.18,label:"HIGH CARD",draw:false}}
function math(state:SolverSpotState){const heroPos=state.hero.position.toUpperCase();const active=state.players.filter(p=>p.action.toUpperCase()!=="FOLD"&&p.position.toUpperCase()!==heroPos);const heroBlind=state.street==="PREFLOP"?(heroPos==="SB"?.5:heroPos==="BB"?1:0):0;const maxCommit=Math.max(0,...state.players.filter(p=>p.action.toUpperCase()!=="FOLD").map(p=>p.value));const toCall=Math.max(0,maxCommit-heroBlind);const potOdds=toCall>0?toCall/(Math.max(0,state.pot)+toCall):0;const eff=Math.min(state.hero.stack,...(active.length?active.map(p=>p.stack):[state.hero.stack]));return{toCall,potOdds,spr:state.pot>0?eff/state.pot:0,opponents:active.length,multiway:active.length>1}}
function softmax(scores:Record<string,number>,legal:PlayerAction[]){const vals=legal.map(a=>({a,v:scores[a]??-20})),max=Math.max(...vals.map(x=>x.v)),exps=vals.map(x=>({a:x.a,e:Math.exp((x.v-max)*3.5)})),sum=exps.reduce((s,x)=>s+x.e,0)||1;let f=exps.map(x=>({action:x.a,frequency:Math.round(x.e/sum*1000)/10}));const total=f.reduce((s,x)=>s+x.frequency,0);if(f.length)f[0].frequency=round(f[0].frequency+100-total,1);const sorted=[...f].sort((a,b)=>b.frequency-a.frequency),best=sorted[0]?.frequency??0,worst=sorted.at(-1)?.frequency??0;return sorted.map(x=>({action:x.action,frequency:x.frequency,classification:(x.frequency===best?"MAIOR EV":x.frequency===worst?"MENOR EV":"MISTA") as TechnicalActionMix["classification"]}))}
export function analyzeTechnicalDecision(state:SolverSpotState,selectedAction:PlayerAction,legalActions:PlayerAction[]):TechnicalDecision{const m=math(state),hand=state.street==="PREFLOP"?preflopStrength(state):postflopStrength(state),scenario=state.scenario.join(" ").toUpperCase(),icm=state.mode==="TORNEIO"&&(scenario.includes("ICM")||scenario.includes("BOLHA")||scenario.includes("FT"));let equity=hand.strength;
// Multiway equity is not heads-up equity: every additional live opponent sharply reduces realization.
if(m.opponents>1)equity*=Math.pow(.72,m.opponents-1);if(state.street==="PREFLOP"&&m.toCall>=8)equity-=.07;if(state.street==="PREFLOP"&&m.toCall>=12)equity-=.07;if(icm)equity-=.035;equity=clamp(equity,.02,.96);
const margin=equity-m.potOdds,score:Record<string,number>={FOLD:-20,CHECK:-20,CALL:-20,BET:-20,RAISE:-20,"ALL-IN":-20};
if(m.toCall>0){score.FOLD=1.3-margin*5+(m.multiway?.25:0)+(icm?.2:0);score.CALL=.9+margin*6-(m.multiway?.45:0)-(m.toCall>=12?.18:0);score.RAISE=.45+equity*2.2-(m.multiway?.30:0)-(icm?.2:0);score["ALL-IN"]=.05+equity*2.4+(m.spr<=1.5?.35:0)-(m.multiway?.4:0)-(icm?.35:0)}else{score.CHECK=1.1+(1-equity)*.5;score.BET=.7+equity*2;score.RAISE=score.BET;score["ALL-IN"]=-.2+equity*2.2+(m.spr<=1?.4:0)}
const legal=[...new Set(legalActions)],mix=softmax(score,legal),chosen=mix.find(x=>x.action===selectedAction),best=mix[0];let verdict:TechnicalDecision["verdict"]="AÇÃO INCORRETA (-EV)";if(chosen&&best){if(chosen.action===best.action||chosen.frequency>=best.frequency*.75)verdict="AÇÃO CORRETA (+EV)";else if(chosen.frequency>=8)verdict="AÇÃO AJUSTÁVEL (MISTA / EV NEUTRO)"}const summary=`${hand.label} · EQ. BASE ${round(equity*100,1)}% · POT ODDS ${round(m.potOdds*100,1)}% · SPR ${round(m.spr,2)}${icm?" · PRESSÃO ICM":""}${m.multiway?` · MULTIWAY ${m.opponents+1}-WAY`:""}`;return{verdict,mix,summary,handClass:hand.label,estimatedEquity:round(equity*100,1),potOdds:round(m.potOdds*100,1),spr:round(m.spr,2)}}
