import type {PlayerAction} from "@/data/player-dna-spots";
import type {SolverSpotState} from "@/lib/player-dna-solver-v2";

export type TechnicalActionMix={action:PlayerAction;frequency:number;classification:"MAIOR EV"|"MISTA"|"MENOR EV"};
export type TechnicalDecision={
  verdict:"AÇÃO CORRETA (+EV)"|"AÇÃO AJUSTÁVEL (MISTA / EV NEUTRO)"|"AÇÃO INCORRETA (-EV)";
  mix:TechnicalActionMix[];
  summary:string;
  handClass:string;
  estimatedEquity:number;
  potOdds:number;
  spr:number;
  mdf:number;
  effectiveStack:number;
  confidence:"ALTA"|"MÉDIA"|"BAIXA";
  bestAction:PlayerAction;
  diagnostics:string[];
};

const rankValue:Record<string,number>={"2":2,"3":3,"4":4,"5":5,"6":6,"7":7,"8":8,"9":9,"T":10,"J":11,"Q":12,"K":13,"A":14};
const positionRank:Record<string,number>={SB:0,BB:1,UTG:2,"UTG+1":3,UTG1:3,"UTG+2":4,UTG2:4,MP:5,MP1:5,MP2:6,"MP+1":6,LJ:7,HJ:8,CO:9,BTN:10};
function clamp(v:number,min=0,max=1){return Math.max(min,Math.min(max,v))}
function round(v:number,p=1){const f=10**p;return Math.round(v*f)/f}
function parseCard(card:string){const c=card.trim().toUpperCase();return{rank:c[0]??"2",suit:c.slice(1)}}
function combinations<T>(items:T[],k:number){const out:T[][]=[];const walk=(start:number,pick:T[])=>{if(pick.length===k){out.push(pick);return}for(let i=start;i<items.length;i++)walk(i+1,[...pick,items[i]])};walk(0,[]);return out}
function fiveCardRank(raw:{rank:string;suit:string}[]){const values=raw.map(c=>rankValue[c.rank]??2).sort((a,b)=>b-a),counts=new Map<number,number>();values.forEach(v=>counts.set(v,(counts.get(v)??0)+1));const groups=[...counts.entries()].sort((a,b)=>b[1]-a[1]||b[0]-a[0]),unique=[...new Set(values)];if(unique.includes(14))unique.push(1);let straightHigh=0;for(let high=14;high>=5;high--){if([0,1,2,3,4].every(d=>unique.includes(high-d))){straightHigh=high;break}}const flush=raw.every(c=>c.suit===raw[0].suit);if(flush&&straightHigh)return{cat:8,label:"STRAIGHT FLUSH",score:8e6+straightHigh};if(groups[0][1]===4)return{cat:7,label:"QUADRA",score:7e6+groups[0][0]*100+groups[1][0]};if(groups[0][1]===3&&groups[1][1]===2)return{cat:6,label:"FULL HOUSE",score:6e6+groups[0][0]*100+groups[1][0]};if(flush)return{cat:5,label:"FLUSH",score:5e6+values.reduce((s,v,i)=>s+v*10**(4-i),0)};if(straightHigh)return{cat:4,label:"SEQUÊNCIA",score:4e6+straightHigh};if(groups[0][1]===3)return{cat:3,label:"TRINCA",score:3e6+groups[0][0]*10000};if(groups[0][1]===2&&groups[1][1]===2){const p=[groups[0][0],groups[1][0]].sort((a,b)=>b-a);return{cat:2,label:"DOIS PARES",score:2e6+p[0]*10000+p[1]*100+(groups[2]?.[0]??0)}}if(groups[0][1]===2)return{cat:1,label:"PAR",score:1e6+groups[0][0]*10000};return{cat:0,label:"HIGH CARD",score:values.reduce((s,v,i)=>s+v*10**(4-i),0)}}
function postflopStrength(state:SolverSpotState){const all=[...state.hero.cards,...state.board].map(parseCard);if(all.length<5)return{strength:.2,label:"MÃO NÃO CLASSIFICADA",draw:false,nutty:false};const best=combinations(all,5).map(fiveCardRank).sort((a,b)=>b.score-a.score)[0],boardOnly=state.board.length>=5?fiveCardRank(state.board.slice(0,5).map(parseCard)):null;let strength=[.16,.37,.61,.74,.82,.88,.94,.975,.995][best.cat]??.16;if(boardOnly&&boardOnly.cat===best.cat&&best.cat<=2)strength-=.08;const suits=new Map<string,number>();all.forEach(c=>suits.set(c.suit,(suits.get(c.suit)??0)+1));const flushDraw=[...suits.values()].some(v=>v===4)&&best.cat<5;const heroRanks=state.hero.cards.map(parseCard).map(c=>rankValue[c.rank]??2),boardRanks=state.board.map(parseCard).map(c=>rankValue[c.rank]??2),topBoard=Math.max(0,...boardRanks);if(best.cat===1&&heroRanks.some(r=>r===topBoard))strength+=.07;return{strength:clamp(strength,.04,.995),label:best.label,draw:flushDraw,nutty:best.cat>=4}}
function preflopStrength(state:SolverSpotState){const h=state.hero.cards.map(parseCard);if(h.length<2)return{strength:.2,label:"MÃO NÃO CLASSIFICADA",draw:false,nutty:false};const a=rankValue[h[0].rank]??2,b=rankValue[h[1].rank]??2,hi=Math.max(a,b),lo=Math.min(a,b),pair=a===b,suited=h[0].suit===h[1].suit,gap=hi-lo;let s=.06+(hi-2)/12*.24+(lo-2)/12*.10;if(pair)s=.28+(hi-2)/12*.55;if(suited)s+=.04;if(gap===1)s+=.03;else if(gap===2)s+=.015;if(hi===14&&lo>=10)s+=.12;if(hi===13&&lo>=11)s+=.06;if(hi<=12&&lo<=9&&!suited&&gap>=3)s-=.06;return{strength:clamp(s,.03,.97),label:pair?`${h[0].rank}${h[1].rank}`:`${h[0].rank}${h[1].rank}${suited?"S":"O"}`,draw:false,nutty:pair&&hi>=12||hi===14&&lo>=13}}
function math(state:SolverSpotState){const heroPos=state.hero.position.toUpperCase(),active=state.players.filter(p=>p.action.toUpperCase()!=="FOLD"&&p.position.toUpperCase()!==heroPos),blind=state.street==="PREFLOP"?(heroPos==="SB"?.5:heroPos==="BB"?1:0):0,maxCommit=Math.max(0,...state.players.filter(p=>p.action.toUpperCase()!=="FOLD").map(p=>p.value)),toCall=Math.max(0,state.heroToCall??(maxCommit-blind)),pot=Math.max(0,state.pot),potOdds=toCall>0?toCall/(pot+toCall):0,eff=Math.max(0,Math.min(state.hero.stack,...(active.length?active.map(p=>p.stack):[state.hero.stack]))),spr=pot>0?eff/pot:0,mdf=toCall>0&&pot>0?pot/(pot+toCall):1;return{toCall,potOdds,spr,mdf,opponents:active.length,multiway:active.length>1,effective:eff}}
function texture(state:SolverSpotState){if(state.street==="PREFLOP")return{wet:false,paired:false,monotone:false,high:false};const cards=state.board.map(parseCard),ranks=cards.map(c=>rankValue[c.rank]??2),suits=cards.map(c=>c.suit),paired=new Set(ranks).size<ranks.length,monotone=cards.length>=3&&new Set(suits).size===1,sorted=[...new Set(ranks)].sort((a,b)=>a-b);let connected=false;for(let i=0;i<sorted.length;i++)for(let j=i+1;j<sorted.length;j++)if(sorted[j]-sorted[i]<=4&&j-i>=2)connected=true;return{wet:monotone||connected,paired,monotone,high:Math.max(0,...ranks)>=12}}
function positionalFactor(state:SolverSpotState){const hero=positionRank[state.hero.position.toUpperCase()]??5;const active=state.players.filter(p=>p.action.toUpperCase()!=="FOLD"&&p.position.toUpperCase()!==state.hero.position.toUpperCase()).map(p=>positionRank[p.position.toUpperCase()]??5);if(!active.length)return 0;const avg=active.reduce((a,b)=>a+b,0)/active.length;return hero>avg?.04:hero<avg?-.035:0}
function pressureProfile(state:SolverSpotState){const h=state.actionHistory??[];const raises=h.filter(x=>x.action.toUpperCase()==="RAISE").length,allins=h.filter(x=>x.action.toUpperCase()==="ALL-IN").length,calls=h.filter(x=>x.action.toUpperCase()==="CALL").length;return{raises,allins,calls,aggression:raises+allins*2}}
function sizingRisk(selectedSizing?:string){if(!selectedSizing)return 0;const s=selectedSizing.toUpperCase();if(s.includes("150%"))return .18;if(s.includes("125%"))return .12;if(s.includes("POT"))return .08;if(s.includes("4X"))return .12;if(s.includes("3X"))return .07;if(s.includes("SQUEEZE"))return .11;return 0}
function rankActions(scores:Record<string,number>,legal:PlayerAction[]){const uniq=[...new Set(legal)],sorted=uniq.map(action=>({action,score:scores[action]??-99})).sort((a,b)=>b.score-a.score),best=sorted[0]?.score??0,worst=sorted.at(-1)?.score??0;return sorted.map(x=>({action:x.action,frequency:0,classification:(best-x.score<=.10?"MAIOR EV":x.score-worst<=.10?"MENOR EV":"MISTA") as TechnicalActionMix["classification"]}))}
function confidence(state:SolverSpotState,m:{multiway:boolean},icm:boolean){let score=3;if(m.multiway)score--;if(icm&&(!state.payouts?.length||!state.fieldStacks?.length))score--;if(state.mode==="CASH"&&state.rakePct===undefined)score--;return score>=3?"ALTA":score===2?"MÉDIA":"BAIXA" as const}

export function analyzeTechnicalDecision(state:SolverSpotState,selectedAction:PlayerAction,legalActions:PlayerAction[],selectedSizing?:string):TechnicalDecision{
  const m=math(state),hand=state.street==="PREFLOP"?preflopStrength(state):postflopStrength(state),board=texture(state),pressure=pressureProfile(state),scenario=state.scenario.join(" ").toUpperCase(),icm=state.mode==="TORNEIO"&&(scenario.includes("ICM")||scenario.includes("BOLHA")||scenario.includes("FT"));let strength=hand.strength+positionalFactor(state);
  if(m.opponents>1)strength*=Math.pow(.76,m.opponents-1);if(state.street==="PREFLOP"){strength-=Math.min(.24,pressure.aggression*.055);if(m.toCall>=8)strength-=.05;if(m.toCall>=12)strength-=.06;if(m.toCall>=20)strength-=.06;if(m.multiway)strength-=.04;if(state.hero.position.toUpperCase()==="SB")strength-=.025}else{if(board.wet&&!hand.nutty)strength-=.03;if(m.multiway&&!hand.nutty)strength-=.06;if(hand.draw)strength+=.035}
  if(icm){strength-=m.effective<=25?.08:.04;if(m.multiway)strength-=.04}strength=clamp(strength,.01,.995);
  const margin=strength-m.potOdds,score:Record<string,number>={FOLD:-99,CHECK:-99,CALL:-99,BET:-99,RAISE:-99,"ALL-IN":-99};
  if(m.toCall>0){score.FOLD=.55-margin*3.8+(m.multiway?.30:0)+(icm?.20:0)+(pressure.aggression>=2?.12:0);score.CALL=.45+margin*4.8-(m.multiway?.30:0)-(pressure.aggression>=2?.14:0)-(icm?.10:0);score.RAISE=.08+strength*1.95+(hand.draw?.10:0)+(hand.nutty?.20:0)-(m.multiway?.28:0)-(icm?.18:0)-sizingRisk(selectedSizing);score["ALL-IN"]=-.12+strength*2.15+(m.spr<=1.5?.34:0)+(hand.nutty?.22:0)-(m.multiway?.34:0)-(icm?.38:0)}else{score.CHECK=.58+(1-strength)*.50+(board.wet&&!hand.nutty?.10:0);score.BET=.30+strength*1.75+(hand.draw?.10:0)+(board.high?.04:0)-sizingRisk(selectedSizing);score.RAISE=score.BET-.05;score["ALL-IN"]=-.18+strength*2+(m.spr<=1?.36:0)+(hand.nutty?.16:0)-(icm?.25:0)}
  if(state.street==="PREFLOP"&&m.multiway&&m.toCall>=10&&!hand.nutty){score.FOLD+=.35;score.CALL-=.32;score.RAISE-=.15;score["ALL-IN"]-=.25}
  const legal=[...new Set(legalActions)],mix=rankActions(score,legal),best=mix[0]?.action??selectedAction,chosenScore=score[selectedAction]??-99,bestScore=Math.max(...legal.map(a=>score[a]??-99)),gap=bestScore-chosenScore;let verdict:TechnicalDecision["verdict"]="AÇÃO AJUSTÁVEL (MISTA / EV NEUTRO)";if(gap<=.10)verdict="AÇÃO CORRETA (+EV)";else if(gap>=.48)verdict="AÇÃO INCORRETA (-EV)";
  const conf=confidence(state,m,icm),diagnostics=[`${hand.label} · FORÇA RELATIVA ${round(strength*100,1)}%`,`${m.multiway?`MULTIWAY ${m.opponents+1}-WAY`:"HEADS-UP"} · STACK EFETIVO ${round(m.effective,1)} BB`,`${m.toCall>0?`POT ODDS ${round(m.potOdds*100,1)}% · MDF ${round(m.mdf*100,1)}%`:`SPR ${round(m.spr,2)} · AÇÃO LIVRE`}`,`${pressure.aggression>=2?"ALTA PRESSÃO DE RANGE":pressure.calls>0?"RANGE MULTI-CALL":"PRESSÃO PADRÃO"}${icm?" · RISK PREMIUM ICM":""}`];
  const summary=`${hand.label} · ${m.multiway?"MULTIWAY":"HEADS-UP"} · POT ODDS ${round(m.potOdds*100,1)}% · SPR ${round(m.spr,2)} · CONFIANÇA ${conf}`;
  return{verdict,mix,summary,handClass:hand.label,estimatedEquity:round(strength*100,1),potOdds:round(m.potOdds*100,1),spr:round(m.spr,2),mdf:round(m.mdf*100,1),effectiveStack:round(m.effective,1),confidence:conf,bestAction:best,diagnostics};
}
